Language: Default (ENG)
Style: Dark_Mode
LastApplied:
  SrcExe: C:/Users/Albin/Downloads/2015-11-04aRagexe/2015-11-04aRagexe.exe
  TgtExe: C:/Users/Albin/Downloads/2015-11-04aRagexe/2015-11-04aRagexe_patched.exe
GenTgtSession: true
ShowVersion: true